SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE TRIGGER dbo.OnKeyTableInsertUpdate  
on KEYTABLE  
for INSERT, UPDATE   
NOT FOR REPLICATION 
AS  
IF @@ROWCOUNT = 0 
     RETURN  
IF UPDATE(IMALOCK) 
BEGIN  
UPDATE KEYTABLE   
SET changestamp = GETUTCDATE()  
WHERE NODEID IN (SELECT NODEID FROM INSERTED)   
END  
GO
